export enum Operation {
  ACCOUNT_CREATE = "ACCOUNT_CREATE",
  ACCOUNT_UPDATE = "ACCOUNT_UPDATE",
  ACCOUNT_CLOSE = "ACCOUNT_CLOSE",
  ACCOUNT_GET = "ACCOUNT_GET",
  ACCOUNT_LIST = "ACCOUNT_LIST",
  ACCOUNT_SUMMARY = "ACCOUNT_SUMMARY",

  AUTH_REGISTER = "AUTH_REGISTER",
  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_ME = "AUTH_ME",

  TRANSACTION_CREATE = "TRANSACTION_CREATE",
  TRANSACTION_GET = "TRANSACTION_GET",
  TRANSACTION_LIST = "TRANSACTION_LIST",

  TRANSFER_CREATE = "TRANSFER_CREATE",
  TRANSFER_GET = "TRANSFER_GET",
  TRANSFER_LIST = "TRANSFER_LIST",
}